import { pgTable, uuid, varchar, text, timestamp, boolean, integer, index } from 'drizzle-orm/pg-core';
import { sexEnum, doctorApprovalStatusEnum, medicalLicenseLevelEnum, philHealthAccreditationEnum, subscriptionTierEnum } from './enums.js';
import { users } from './user.schema.js';

export const doctorInfos = pgTable(
  'DoctorInfo',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('userId').notNull().unique().references(() => users.id),
    firstName: varchar('firstName', { length: 255 }).notNull(),
    middleName: varchar('middleName', { length: 255 }),
    lastName: varchar('lastName', { length: 255 }).notNull(),
    gender: sexEnum('gender').notNull(),
    dateOfBirth: timestamp('dateOfBirth').notNull(),
    contactNumber: varchar('contactNumber', { length: 50 }).notNull(),
    address: text('address').notNull(),
    bio: text('bio').notNull(),
    specialization: varchar('specialization', { length: 255 }).notNull(),
    qualifications: text('qualifications').notNull(),
    experience: integer('experience').notNull(),
    prcId: varchar('prcId', { length: 255 }),
    ptrId: varchar('ptrId', { length: 255 }),
    medicalLicenseLevel: medicalLicenseLevelEnum('medicalLicenseLevel'),
    philHealthAccreditation: philHealthAccreditationEnum('philHealthAccreditation'),
    licenseNumber: varchar('licenseNumber', { length: 255 }),
    licenseExpiry: timestamp('licenseExpiry'),
    isLicenseActive: boolean('isLicenseActive').default(true).notNull(),
    additionalCertifications: text('additionalCertifications'),
    licenseIssuedBy: varchar('licenseIssuedBy', { length: 255 }),
    licenseIssuedDate: timestamp('licenseIssuedDate'),
    renewalRequired: boolean('renewalRequired').default(true).notNull(),
    prcIdImage: text('prcIdImage'), // Using text for base64 or JSON
    ptrIdImage: text('ptrIdImage'),
    medicalLicenseImage: text('medicalLicenseImage'),
    additionalIdImages: text('additionalIdImages'),
    idDocumentsVerified: boolean('idDocumentsVerified').default(false).notNull(),
    idDocumentsVerifiedBy: varchar('idDocumentsVerifiedBy', { length: 255 }),
    idDocumentsVerifiedAt: timestamp('idDocumentsVerifiedAt'),
    approvalStatus: doctorApprovalStatusEnum('approvalStatus').default('PENDING').notNull(),
    approvalStatusUpdatedBy: varchar('approvalStatusUpdatedBy', { length: 255 }),
    approvalStatusUpdatedAt: timestamp('approvalStatusUpdatedAt'),
    approvalRejectionReason: text('approvalRejectionReason'),
    subscriptionTier: subscriptionTierEnum('subscriptionTier').default('FREE').notNull(),
    maxPatients: integer('maxPatients'),
    currentPatients: integer('currentPatients').default(0).notNull(),
    maxFaceScans: integer('maxFaceScans'),
    currentFaceScans: integer('currentFaceScans').default(0).notNull(),
    subscriptionStartDate: timestamp('subscriptionStartDate'),
    subscriptionEndDate: timestamp('subscriptionEndDate'),
    isSubscriptionActive: boolean('isSubscriptionActive').default(true).notNull(),
  },
  (table) => ({
    subscriptionTierIdx: index('doctorInfo_subscriptionTier_idx').on(table.subscriptionTier),
    isSubscriptionActiveIdx: index('doctorInfo_isSubscriptionActive_idx').on(table.isSubscriptionActive),
    prcIdIdx: index('doctorInfo_prcId_idx').on(table.prcId),
    ptrIdIdx: index('doctorInfo_ptrId_idx').on(table.ptrId),
    medicalLicenseLevelIdx: index('doctorInfo_medicalLicenseLevel_idx').on(table.medicalLicenseLevel),
    philHealthAccreditationIdx: index('doctorInfo_philHealthAccreditation_idx').on(table.philHealthAccreditation),
    isLicenseActiveIdx: index('doctorInfo_isLicenseActive_idx').on(table.isLicenseActive),
    licenseExpiryIdx: index('doctorInfo_licenseExpiry_idx').on(table.licenseExpiry),
    idDocumentsVerifiedIdx: index('doctorInfo_idDocumentsVerified_idx').on(table.idDocumentsVerified),
    idDocumentsVerifiedByIdx: index('doctorInfo_idDocumentsVerifiedBy_idx').on(table.idDocumentsVerifiedBy),
    approvalStatusIdx: index('doctorInfo_approvalStatus_idx').on(table.approvalStatus),
  }),
).enableRLS();
