import { pgTable, uuid, varchar, real, boolean, integer, timestamp } from 'drizzle-orm/pg-core';
import { consultations } from './consultation.schema.js';

export const healthScans = pgTable('HealthScan', {
  id: uuid('id').primaryKey().defaultRandom(),
  consultationId: uuid('consultationId').notNull().unique().references(() => consultations.id),
  bloodPressure: varchar('bloodPressure', { length: 20 }),
  heartRate: real('heartRate'),
  spO2: real('spO2'),
  respiratoryRate: real('respiratoryRate'),
  stressLevel: real('stressLevel'),
  stressScore: real('stressScore'),
  hrvSdnn: real('hrvSdnn'),
  hrvRmsdd: real('hrvRmsdd'),
  generalWellness: real('generalWellness'),
  generalRisk: real('generalRisk'),
  coronaryHeartDisease: real('coronaryHeartDisease'),
  congestiveHeartFailure: real('congestiveHeartFailure'),
  intermittentClaudication: real('intermittentClaudication'),
  strokeRisk: real('strokeRisk'),
  covidRisk: real('covidRisk'),
  height: real('height'),
  weight: real('weight'),
  smoker: boolean('smoker'),
  hypertension: boolean('hypertension'),
  bpMedication: boolean('bpMedication'),
  diabetic: integer('diabetic'),
  waistCircumference: real('waistCircumference'),
  heartDisease: boolean('heartDisease'),
  depression: boolean('depression'),
  totalCholesterol: real('totalCholesterol'),
  hdl: real('hdl'),
  parentalHypertension: integer('parentalHypertension'),
  physicalActivity: boolean('physicalActivity'),
  healthyDiet: boolean('healthyDiet'),
  antiHypertensive: boolean('antiHypertensive'),
  historyBloodGlucose: boolean('historyBloodGlucose'),
  historyFamilyDiabetes: integer('historyFamilyDiabetes'),
}).enableRLS();
