import { pgTable, uuid, varchar, text, timestamp, boolean, integer, real, index } from 'drizzle-orm/pg-core';
import { sexEnum, patientVerificationStatusEnum, subscriptionTierEnum } from './enums.js';
import { users } from './user.schema.js';

export const patientInfos = pgTable(
  'PatientInfo',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('userId').notNull().unique().references(() => users.id),
    firstName: varchar('firstName', { length: 255 }).notNull(),
    middleName: varchar('middleName', { length: 255 }),
    lastName: varchar('lastName', { length: 255 }).notNull(),
    gender: sexEnum('gender').notNull(),
    dateOfBirth: timestamp('dateOfBirth').notNull(),
    contactNumber: varchar('contactNumber', { length: 50 }).notNull(),
    address: text('address').notNull(),
    weight: real('weight').notNull(),
    height: real('height').notNull(),
    bloodType: varchar('bloodType', { length: 10 }).notNull(),
    medicalHistory: text('medicalHistory'),
    allergies: text('allergies'),
    medications: text('medications'),
    philHealthId: varchar('philHealthId', { length: 50 }),
    philHealthStatus: varchar('philHealthStatus', { length: 50 }),
    philHealthCategory: varchar('philHealthCategory', { length: 50 }),
    philHealthExpiry: timestamp('philHealthExpiry'),
    philHealthMemberSince: timestamp('philHealthMemberSince'),
    philHealthIdImage: text('philHealthIdImage'),
    philHealthIdVerified: boolean('philHealthIdVerified').default(false).notNull(),
    philHealthIdVerifiedBy: varchar('philHealthIdVerifiedBy', { length: 255 }),
    philHealthIdVerifiedAt: timestamp('philHealthIdVerifiedAt'),
    verificationStatus: patientVerificationStatusEnum('verificationStatus').default('NOT_VERIFIED').notNull(),
    verificationStatusUpdatedBy: varchar('verificationStatusUpdatedBy', { length: 255 }),
    verificationStatusUpdatedAt: timestamp('verificationStatusUpdatedAt'),
    verificationRejectionReason: text('verificationRejectionReason'),
    subscriptionTier: subscriptionTierEnum('subscriptionTier').default('FREE').notNull(),
    maxFaceScans: integer('maxFaceScans'),
    currentFaceScans: integer('currentFaceScans').default(0).notNull(),
    subscriptionStartDate: timestamp('subscriptionStartDate'),
    subscriptionEndDate: timestamp('subscriptionEndDate'),
    isSubscriptionActive: boolean('isSubscriptionActive').default(true).notNull(),
  },
  (table) => ({
    subscriptionTierIdx: index('patientInfo_subscriptionTier_idx').on(table.subscriptionTier),
    isSubscriptionActiveIdx: index('patientInfo_isSubscriptionActive_idx').on(table.isSubscriptionActive),
    philHealthIdIdx: index('patientInfo_philHealthId_idx').on(table.philHealthId),
    philHealthStatusIdx: index('patientInfo_philHealthStatus_idx').on(table.philHealthStatus),
    philHealthIdVerifiedIdx: index('patientInfo_philHealthIdVerified_idx').on(table.philHealthIdVerified),
    philHealthIdVerifiedByIdx: index('patientInfo_philHealthIdVerifiedBy_idx').on(table.philHealthIdVerifiedBy),
    verificationStatusIdx: index('patientInfo_verificationStatus_idx').on(table.verificationStatus),
    verificationStatusUpdatedByIdx: index('patientInfo_verificationStatusUpdatedBy_idx').on(table.verificationStatusUpdatedBy),
  }),
).enableRLS();
